typedef enum {
	scmodHeader,     /*  0 */
	import,          /*  1 */
	dataSize,        /*  2 */
	filledData,      /*  3 */
	procCode,        /*  4 */
	initCode,        /*  5 */
	scmodInitCode,   /*  6 */
	excpCode,        /*  7 */
	refOwnData,      /*  8 */
	refExtData,      /*  9 */
	refOwnCode,      /* 10 */
	refOwnProcCall,  /* 11 */
	refExtProcCall,  /* 12 */
	refOwnProcAss,   /* 13 */
	refExtProcAss,   /* 14 */
	refOwnExcp,      /* 15 */
	refExtExcp,      /* 16 */
	refExtInitCall,  /* 17 */
	scmodEnd,        /* 18 */
	linkCodeVersion, /* 19 */
	refAnyProcCall,  /* 20 */
	refAnyProcAss,   /* 21 */
	stringData,      /* 22 */
	boundData,       /* 23 */
	refOwnString,    /* 24 */
	refOwnBound,     /* 25 */
	refUtil,         /* 26 */
	loadUtil,        /* 27 */
	defAbsSymbol,    /* 28 */
	refAbsSymbol,    /* 29 */
	reserved1,       /* 30 */
	reserved2,       /* 31 */
	refOwnQuickCall, /* 32 */
	refOwnQuickAss,  /* 33 */
	refExtQuickCall, /* 34 */
	refExtQuickAss   /* 35 */
} LnkFileSymbols;
